/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redsocial;

import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;

/**
 *
 * @author ricardoi
 */
public class Estadistica extends javax.swing.JInternalFrame {

    final JFXPanel fxPanel;
    
    
    /**
     * Creates new form iniciarSesion
     * @param title
     */
    public Estadistica(String title) {
        initComponents();
        
//        Connection<User> friends = UIInicio.client.fetchConnection("me/friends", User.class);
//        
//        Connection<NamedFacebookType> connection = UIInicio.client.fetchConnection("me/friends", NamedFacebookType.class);
//    
//    List<NamedFacebookType> allFriends = connection.getData();
        
        
        
        this.setTitle(title);

        fxPanel = new JFXPanel();
        fxPanel.setSize(this.getWidth(), this.getHeight());
        add(fxPanel);

        Platform.runLater(new Runnable() {
            @Override
            public void run() {

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
