/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redsocial;

import com.restfb.DefaultFacebookClient;
import com.restfb.FacebookClient;
import com.restfb.Version;
import com.restfb.scope.FacebookPermissions;
import com.restfb.scope.ScopeBuilder;
import javafx.application.Platform;
import javafx.beans.value.ObservableValue;
import javafx.concurrent.Worker;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javax.swing.JDesktopPane;

/**
 *
 * @author ricardoi
 */
public class iniciarSesion extends javax.swing.JInternalFrame {

    final JFXPanel fxPanel;
    String loginDialogUrlString;
    String fbauthcode = "";
    FacebookClient fbclient;
//    final String appid = "114238339453336";
    final String appid = "200029144054336";
    final String success_url = "https://www.facebook.com/connect/login_success.html";
//    final String appsecret = "8d67ced08ce9d75dd52f4077602f75be";
    final String appsecret = "baef04c73e97f3256a4b2ae91ff5a356";
    private JDesktopPane desktopPane;

    /**
     * Creates new form iniciarSesion
     */
    public iniciarSesion() {
        initComponents();

        ScopeBuilder scopeBuilder = new ScopeBuilder();
        scopeBuilder.addPermission(FacebookPermissions.EMAIL);
        scopeBuilder.addPermission(FacebookPermissions.PUBLIC_PROFILE);
        scopeBuilder.addPermission(FacebookPermissions.USER_FRIENDS);
        scopeBuilder.addPermission(FacebookPermissions.USER_PHOTOS);
        scopeBuilder.addPermission(FacebookPermissions.USER_POSTS);
        scopeBuilder.addPermission(FacebookPermissions.USER_MANAGED_GROUPS);

        fbclient = new DefaultFacebookClient(Version.VERSION_2_12);
        loginDialogUrlString = fbclient.getLoginDialogUrl(appid, success_url, scopeBuilder);
        System.out.println("url");
        System.out.println(loginDialogUrlString);

        fxPanel = new JFXPanel();
        fxPanel.setSize(this.getWidth(), this.getHeight());
        add(fxPanel);

        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                cargarUrl(fxPanel);
            }
        });

    }

    private void cargarUrl(JFXPanel fxPanel) {

        WebView browser = new WebView();
        WebEngine webEngine = browser.getEngine();
        fxPanel.setScene(new Scene(browser));
        webEngine.load(loginDialogUrlString);
        webEngine.getLoadWorker().stateProperty().addListener(
                (ObservableValue<? extends Worker.State> observable, Worker.State oldValue, Worker.State newValue) -> {
                    if (newValue != Worker.State.SUCCEEDED) {
                        return;
                    }

                    String myUrl = webEngine.getLocation();

                    if ("https://www.facebook.com/dialog/close".equals(myUrl)) {
                        System.out.println("dialog closed");
                        System.exit(0);
                    }

                    if (myUrl.startsWith(success_url)) {
                        System.out.println(myUrl);
                        int pos = myUrl.indexOf("code=");
                        fbauthcode = myUrl.substring(pos + "code=".length());
                        UIInicio.tokendeUsuario = fbclient.obtainUserAccessToken(appid,
                                appsecret, success_url, fbauthcode);
                        UIInicio.client = new DefaultFacebookClient(UIInicio.tokendeUsuario.getAccessToken(), Version.LATEST);
                        /*System.out.println("Accesstoken: " + tokendeUsuario.getAccessToken());
                         System.out.println("Expires: " + tokendeUsuario.getExpires());*/
                        this.dispose();
                    }

                });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
