package redsocial;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.restfb.Connection;
import com.restfb.json.JsonObject;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricardoi
 */
public class UltimosPost extends javax.swing.JInternalFrame {

    final JFXPanel fxPanel;

    /**
     * Creates new form iniciarSesion
     *
     * @param title
     */
    public UltimosPost(String title) {
        initComponents();

        cargarTablaConDatos();
        this.setTitle(title);

        fxPanel = new JFXPanel();
        fxPanel.setSize(this.getWidth(), this.getHeight());
        add(fxPanel);

        Platform.runLater(new Runnable() {
            @Override
            public void run() {

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaConDatos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("id");
        modelo.addColumn("name");
        modelo.addColumn("fecha");
        
        Connection<com.restfb.json.JsonObject> feedConnection = UIInicio.client.fetchConnection("me/feed", com.restfb.json.JsonObject.class);
        
        for (int x = 0; x < feedConnection.getData().size(); x++) {
            Object[] fila = new Object[3];
            JsonObject obj = feedConnection.getData().get(x);
            if (!obj.isEmpty()) {
                fila[0] = obj.getString("id","");
                fila[1] = obj.getString("message","");
                fila[2] = obj.getString("created_time","");
                modelo.addRow(fila); // Añade una fila al final del modelo de la tabla
            }
        }
        jTable1 = new JTable(modelo);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setPreferredWidth(300);
        jTable1.getTableHeader().getColumnModel().getColumn(1).setPreferredWidth(300);
        jTable1.getTableHeader().getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.updateUI();
    }
}
